Added:  CalendarScreen.kt  CalendarVIewModel.kt
 Created MyApp.kt to initialize FirebaseApp as first because of:
 IllegalStateException: Default FirebaseApp is not initialized

 Updated:
 Navigation.kt
 HomeScreen.kt to get to the CalendarScreen.kt